# Site settings
title: "Justin Roche"
email: jproche5@gmail.com
description: "Developer"
baseurl: ""
# url: "http://carte-noire.jacobtomlinson.co.uk/"
title_description: "Web Development, Node, Emacs, and more"
# title_image: "https://www.gravatar.com/avatar/00000000000000000000000000000000?s=500&d=mm"
google_analytics: ""
disqus_account: http-justin-roche-github-io
github_repository: https://github.com/justin-roche
addthis_id: 0
post_limit: 5

# Social usernames/URLs
# twitter_username: _jacobtomlinson
github_username:  justin-roche
# instagram_username: 
# reddit_username: 
linkedin_link: https://www.linkedin.com/in/justin-roche/
# google_plus_link: http://carte-noire.jacobtomlinson.co.uk/
# stackoverflow_link: http://carte-noire.jacobtomlinson.co.uk/
# xing_link:
# facebook_link:

# Footer
# footer_left: "Carte Noire theme by <a href=\"https://twitter.com/_JacobTomlinson\">Jacob Tomlinson</a>"
# footer_right: "&lt;/&gt; on <a href=\"https://github.com/jacobtomlinson/carte-noire\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
highlighter: rouge
permalink: pretty
exclude: [vendor]
